CREATE TABLE `metricas_subetapa_sembrado` (
	`id` text PRIMARY KEY NOT NULL,
	`lote_id` text NOT NULL,
	`tecnico_id` text NOT NULL,
	`subfase` text NOT NULL,
	`fecha_inicio` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`fecha_fin` text,
	`tasa_germinacion` real,
	`dias_emergencia` integer,
	`presencia_hongos` integer,
	`pares_hojas_verdaderas` integer,
	`altura_plantula` real,
	`vigor_radicular` text,
	`indice_crecimiento` real,
	`grosor_tallo` real,
	`formacion_bandolas` integer,
	`incidencia_foliar` real,
	`intensidad_floracion` text,
	`uniformidad_floracion` text,
	`estres_hidrico` text,
	`porcentaje_cuajado` real,
	`homogeneidad_maduracion` text,
	`incidencia_broca` real,
	`grados_brix` real,
	`is_synced` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`lote_id`) REFERENCES `lotes`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`tecnico_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action
);
